# Generated by Django 5.0.1 on 2024-01-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_category', models.CharField(max_length=50, unique=True)),
                ('Description_category', models.CharField(default='Other', max_length=100)),
                ('Created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Dob', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('MobileNumber', models.PositiveBigIntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('User_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Name', models.CharField(max_length=100)),
                ('Song_Audio_File', models.FileField(upload_to='songs/')),
                ('Song_Artist', models.CharField(max_length=50)),
                ('Song_Image', models.ImageField(upload_to='Song_image/')),
                ('Song_Created', models.DateField(auto_now_add=True)),
                ('Song_updated', models.DateField(auto_now=True)),
                ('Song_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='Admin.genre')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user_info')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user_info'),
        ),
    ]
