# Generated by Django 5.0.1 on 2024-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Song_Lyrics_File',
            field=models.FileField(default='Not Avaliable', upload_to='songs_Lyrics/'),
        ),
    ]
