# Generated by Django 5.0.1 on 2024-01-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_song_song_lyrics_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_play_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayList_Name', models.CharField(default='My_Playlist', max_length=20)),
                ('Song_Created', models.DateField(auto_now_add=True)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user_info')),
                ('Songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.song')),
            ],
        ),
    ]
