# Generated by Django 5.0.1 on 2024-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_add_play_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_play_list',
            name='Songs',
        ),
        migrations.AddField(
            model_name='add_play_list',
            name='Songs',
            field=models.ManyToManyField(related_name='playlists', to='Admin.song'),
        ),
    ]
